project:
  type: website
  output-dir: docs
  render:
    - index.qmd
  resources:
    - CNAME
    - appendix-branches-and-roots/**

website:
  title: "Jean de Oliveira"
  navbar: false
  page-footer:
    center: ""

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: false
    page-layout: article
